Handle err travis (#49)
* travis.yml: use build_ci script in build step

It's better running the build command by a shell script.
With a shell script, easily handle error and enhance in future

One issue can avoid such as in Build #87
lacking of checking the error which make inconsistent result.

* array: fix clang build errors

Explicitly typename for avoiding the error in travis-ci Build #87

error: missing 'typename' prior to dependent type name 'std::array<T, N>::iterator'
    using iterator               = std::array<T, N>::iterator;
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                   typename

* build_ci: enhance options for sanitizer check

Add more options for difference b_sanitize option.
Enable in travis ci with address,undefined.

* build_ci: disable leak detect in ASAN_OPTIONS